---
title: "Final Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 2 Problem statement and notation recreation by simulating 
set.seed(42)

# sample size of n independent observations
n <- 500

# length of control variables
d <- 4 

# make four variable for length d = 4 we can prob automate this
X1 <- runif(n, 0, 1)  
X2 <- rnorm(n, 0, 1)  
X3 <- sample(0:1, n, replace = TRUE) 
X4 <- sample(1:3, n, replace = TRUE)

# (nxd) matrix 
X <- data.frame(X1, X2, X3, X4)

logit_pi <- function(X) {
#Pr(z_i=1|x_i) 0.5, 1.2, 0.8, 0.6 are arbitrary
  linear_combination <- -0.5 + 1.2 * X$X1 - 0.8 * X$X2 + 0.6 * X$X3
  return(1 / (1 + exp(-linear_combination))) 
}

# π(xi) = Pr(Zi = 1 | xi).
propensity <- logit_pi(X)


Z <- Z <- rbinom(n, 1, propensity)

# baseline outcomes
mu_X <- -4 + 2 * X$X3 + 3 * abs(X$X2 - 1)


# τ(X) = E[Y | X, Z=1] - E[Y | X, Z=0]
tau_X <- 2 + 1.5 * X$X1 * (X$X4 == 2)

# epsilon = N(0,sigma^2)
eps <- rnorm(n, mean = 0, sd = 1)

#Y_i = Z_iY_i(1) + (1-Z_i)Y_i(0)
Y0 <- mu_X + eps  # Y(0) (control outcome)
Y1 <- mu_X + tau_X + eps  # Y(1) (treated outcome)

Y <-Z * Y1 + (1 - Z) * Y0 
#tau(x_i) = E(Yi | xi, Zi = 1) − E(Yi | xi, Zi = 0)



data <- data.frame(Y, Z, X, tau_X)
head(data)
```

```{r}
library(BART)

bart_model <- wbart(
  x.train = as.matrix(X),
  y.train = Y,
  ntree = 200,
  k = 2,
  power = 2,
  base = 0.95
)

X_treated <- X
Y1_hat <- predict(bart_model, newdata = as.matrix(X_treated))  # E[Y | X, Z=1]

X_untreated <- X
Y0_hat <- predict(bart_model, newdata = as.matrix(X_untreated))  # E[Y | X, Z=0]

tau_hat <- Y1_hat - Y0_hat

results <- data.frame(X, tau_true = tau_X, tau_hat = tau_hat)
head(results)


```

```{r}
# 4. Propensity score in regularized causal model
# not sure where to go from here
library(MASS)

lambda <- c(0.8, -0.3, 0.5, -0.4)  # Selection model coefficients
beta <- abs(c(1, 2, 1.5, 0.5))  # beta memb [0, infinity) 
tau <- 2 

nu <- rnorm(n, mean = 0, sd = 1)  # N(0,1)

#Z = gama^T X + nu
X <- as.matrix(X)

Z <- X %*% lambda + nu  
Z <- ifelse(Z > 0, 1, 0)  
X <- as.matrix(X)

# Compute observed outcome Y = tauZ + beta^T X + eps
Y <- tau * Z + X %*% beta + eps  

# Store data in dataframe
data <- data.frame(Y, Z, X)
```

```{r}

set.seed(42)
n <- 250 
d <- 2  


X1 <- runif(n, 0, 1)
X2 <- runif(n, 0, 1)

mu_X <- X1 - X2

propensity <- 0.8 * (mu_X / (0.1 * (2 - X1 - X2) + 0.25)) + 0.025 * (X1 + X2) + 0.05
propensity <- pmax(0, pmin(1, propensity))

Z <- rbinom(n, 1, propensity)

eps <- rnorm(n, mean = 0, sd = 1)

tau <- 1
Y <- mu_X - tau * Z + eps
data <- data.frame(Y, Z, X1, X2, mu_X, propensity)
head(data)

bart_treated <- wbart(x.train = X[Z == 1, ], y.train = Y[Z == 1])
bart_control <- wbart(x.train = X[Z == 0, ], y.train = Y[Z == 0])


Y_hat_1 <- predict(bart_treated, newdata = X)  
Y_hat_0 <- predict(bart_control, newdata = X) 


tau_hat <- rowMeans(Y_hat_1) - rowMeans(Y_hat_0)


bias <- mean(tau_hat - tau)  
rmse <- sqrt(mean((tau_hat - tau)^2))  

# should match table 1 but does not
cat("Estimated Bias:", bias, "\n")
cat("Estimated RMSE:", rmse, "\n")
```

```{r}
# should be between -2 and 3 an y same as figure 4
library(ggplot2)
ggplot(data, aes(x =propensity , y = mu_X)) +
  geom_point(alpha = 0.2)  +
  labs( x = "pi", y = "mu")

```

```{r}

# to match 4.3 
library(glmnet) 

set.seed(42)


n <- 250  
X1 <- runif(n, 0, 1)
X2 <- runif(n, 0, 1)
X <- cbind(X1, X2)  

mu_X <- X1 - X2  
propensity <- 0.8 * (mu_X / (0.1 * (2 - X1 - X2) + 0.25)) + 0.025 * (X1 + X2) + 0.05
propensity <- pmax(0, pmin(1, propensity))

Z <- rbinom(n, 1, propensity)

tau <- 1  
eps <- rnorm(n, mean = 0, sd = 1)
Y <- mu_X - tau * Z + eps  


propensity_model <- glm(Z ~ X1 + X2, family = binomial)
propensity_hat <- predict(propensity_model, type = "response")  

X_tilde <- cbind(Z, propensity_hat, X1, X2)

library(BART)
bart_model <- wbart(x.train = X_tilde, y.train = Y)

X_tilde_treated <- cbind(1, propensity_hat, X1, X2) 
X_tilde_control <- cbind(0, propensity_hat, X1, X2)  

Y_hat_1 <- predict(bart_model, newdata = X_tilde_treated)
Y_hat_0 <- predict(bart_model, newdata = X_tilde_control)

tau_hat <- rowMeans(Y_hat_1) - rowMeans(Y_hat_0)

bias <- mean(tau_hat - tau)
rmse <- sqrt(mean((tau_hat - tau)^2))

cat("Estimated Bias:", bias, "\n")
cat("Estimated RMSE:", rmse, "\n")


```

```{r}
# section 5.3 
set.seed(42)

n <- 250  
X1 <- runif(n, 0, 1)
X2 <- runif(n, 0, 1)
X <- cbind(X1, X2)  

mu_X <- X1 - X2 
propensity <- 0.8 * (mu_X / (0.1 * (2 - X1 - X2) + 0.25)) + 0.025 * (X1 + X2) + 0.05
propensity <- pmax(0, pmin(1, propensity))  

Z <- rbinom(n, 1, propensity)

b0 <- rnorm(1, mean = 0, sd = sqrt(1/2))  
b1 <- rnorm(1, mean = 0, sd = sqrt(1/2))  

tau_tilde <- 0.5 * X1 + 0.5 * X2  

tau_X <- (b1 - b0) * tau_tilde  

eps <- rnorm(n, mean = 0, sd = 1)  

Y <- mu_X + tau_X * Z + eps  

propensity_model <- glm(Z ~ X1 + X2, family = binomial)
propensity_hat <- predict(propensity_model, type = "response") 

data <- data.frame(Y, Z, X1, X2, mu_X, tau_X, propensity_hat)

head(data)

```

```{r}

library(grf)

set.seed(42)

n <- 250  

X1 <- rnorm(n, 0, 1)
X2 <- rnorm(n, 0, 1)
X3 <- rnorm(n, 0, 1)
X4 <- rbinom(n, 1, 0.5)  
X5 <- sample(1:3, n, replace = TRUE)  

X <- data.frame(X1, X2, X3, X4, X5)
head(X)
```

```{r}
tau_homogeneous <- rep(3, n)  
tau_heterogeneous <- 1 + 2 * X$X2 * X$X5  

X$tau_homogeneous <- tau_homogeneous
X$tau_heterogeneous <- tau_heterogeneous

head(X)

```

```{r}
g_X5 <- ifelse(X$X5 == 1, 2, ifelse(X$X5 == 2, -1, -4))

mu_linear <- 1 + g_X5 + X$X1 * X$X3

mu_nonlinear <- -6 + g_X5 + 6 * abs(X$X3 - 1)

X$mu_linear <- mu_linear
X$mu_nonlinear <- mu_nonlinear

head(X)

```

```{r}

s_linear <- sd(X$mu_linear)
s_nonlinear <- sd(X$mu_nonlinear)

u <- runif(n, 0, 1)

propensity_linear <- 0.8 * ((3 * X$mu_linear / s_linear) - 0.5 * X$X1) + 0.05 + u / 10
propensity_nonlinear <- 0.8 * ((3 * X$mu_nonlinear / s_nonlinear) - 0.5 * X$X1) + 0.05 + u / 10

propensity_linear <- pmax(0, pmin(1, propensity_linear))
propensity_nonlinear <- pmax(0, pmin(1, propensity_nonlinear))

Z_linear <- rbinom(n, 1, propensity_linear)
Z_nonlinear <- rbinom(n, 1, propensity_nonlinear)

X$propensity_linear <- propensity_linear
X$propensity_nonlinear <- propensity_nonlinear
X$Z_linear <- Z_linear
X$Z_nonlinear <- Z_nonlinear

head(X)

```

```{r}
eps <- rnorm(n, mean = 0, sd = 1)

Y_linear_homogeneous <- X$mu_linear + X$tau_homogeneous * X$Z_linear + eps
Y_linear_heterogeneous <- X$mu_linear + X$tau_heterogeneous * X$Z_linear + eps

Y_nonlinear_homogeneous <- X$mu_nonlinear + X$tau_homogeneous * X$Z_nonlinear + eps
Y_nonlinear_heterogeneous <- X$mu_nonlinear + X$tau_heterogeneous * X$Z_nonlinear + eps

X$Y_linear_homogeneous <- Y_linear_homogeneous
X$Y_linear_heterogeneous <- Y_linear_heterogeneous
X$Y_nonlinear_homogeneous <- Y_nonlinear_homogeneous
X$Y_nonlinear_heterogeneous <- Y_nonlinear_heterogeneous

```

```{r}
library(bcf)

set.seed(42)

X_covariates <- as.matrix(X[, c("X1", "X2", "X3", "X4", "X5")])
y <- X$Y_linear_heterogeneous  
z <- X$Z_linear
pihat <- X$propensity_linear  

bcf_model <- bcf(y = y, z = z, x_control = X_covariates, x_moderate = X_covariates, pihat = pihat, nburn = 500, nsim = 1000)

tau_hat <- colMeans(bcf_model$tau)

X$tau_hat_bcf <- tau_hat

head(X[, c("tau_heterogeneous", "tau_hat_bcf")])

```
